### ISSUE TITLE
Add way to customize temporary directory

### ISSUE THREAD

**Issue by notetiene** [Jwink3101/syncrclone#18]
When running **syncrclone**, many files are created at the `/tmp`.  It dumps information about the state of execution.

However, if running syncrclone multiple times, it ends up polluting the `/tmp` directory.  I frequently remove all those files, otherwise I can't list the directory.

Today I ran
```
etienne@localhost:~$ ls /tmp/tmp<tab>
Display all 20017 possibilities? (y or n)
```

I even saw one time ~100k entries.  Is it possible to put those files in something like `/tmp/syncrclone`.

**Comment by Jwink3101** [comment]
Hi,

On the worst-case syncrclone run, there should be at most about 14 temp files. I may be forgetting a code path or two but that is approximately correct. And, 10 of them should be in their own subdir as opposed to all just residing in `/tmp`. So if you have 20_000, that is from about 2000 runs of syncrclone.

Many, many, many programs write to temp space so are you sure that syncrclone is your culprit? Rclone also uses tmp spaces though I don't think it uses many. Still, you can set the location with the `--temp-dir` flag ([docs](https://rclone.org/docs/#temp-dir-dir)). In syncrclone, you would do:

    rclone_flags = ['--temp-dir','mydir']

See if that drops the number.

Anyway, I am hesitant to change the behavior because then I have to think about a platform-specific process. Right now, I use ` tempfile.TemporaryDirectory().name` for the root dir of the 10 or so and that is platform specific. For example, on my mac, I get `/var/folders/mp/n9dd7hhn4mggybcfd1yjz9nw002fv0/T/tmpjzys8pq4` and on my linux VPS, I get `/tmp/tmp988rw9q0`. For a few places, I use `tempfile.NamedTemporaryFile()`.

Furthermore, if it is user-specified, it would have to be unique for each run so that two concurrent syncrclone calls won't clobber each other.

I guess I could have the user optionally specify a temp dir and then make a random directory inside of that. I will consider it but please first confirm that all of the noted cruft is from syncrclone (and/or rclone)

**Comment by notetiene** [comment]
Quick reply!

All the files in question start with `/tmp/tmp[8 char alphanum]` which is precisely what **tempfile** does.  I don't use many python programs and each file I looked at random were clearly syncrclone files.

I've came up with a solution of monkey patching the `tempfile` library.  I might to a pull request.

**Comment by Jwink3101** [comment]
I'd be open to a pull request to set it but I will not accept a monkey-patch. Monkey-patching is super powerful and can be very useful at times but it is also bad practice when it can be avoided. The cost of the technical debt and fragility is not worth it (though I imagine `tempfile` is pretty stable)

**Comment by Jwink3101** [comment]
@notetiene, I **_REALLY_** think your issue is unrelated to syncrclone as very few temp files get created on each run. But, I decided it wasn't too hard to add the option as I just did in 20220228.0.BETA. Let me know if this works out for you.
