### ISSUE TITLE
 Is it possible to separate the algorithm part of this project?

### ISSUE THREAD

**Issue by HengyueLi** [Jwink3101/syncrclone#34]
As a long-time user of rclone who has successfully tested this project, I've found it to be highly effective! Currently, I'm looking to integrate a pure Python sync algorithm into my project, and yours is the most relevant I've found. However, I need to adapt it to use my own API instead of rclone. Could you please guide me on how to isolate the algorithmic component, or provide detailed documentation on how to build upon your project?

**Comment by Jwink3101** [comment]
Thank you for your kind words. I am glad it has been working well for you.

On the surface, it should be pretty doable to adapt to your own API. If you look at the code, almost all transfer functionality is in `rclone.py`. I would suggest abstracting the `rclone.Rclone` object and then adding your own API. I opted not to do that when I developed syncrclone because I didn't want to try to support anything else but I still kept most functionality in the separate object to keep it easier.

An alternative is rather than trying to use my code directly, use it to learn the algorithm and implement it yourself. You could still do selective copy/paste but it may work better than trying to squeeze another API into existing code.

It is also worth reading about sync algorithms. Another way to look at it is via set theory. See http://blog.ezyang.com/2012/08/how-offlineimap-works/ and  https://unterwaditzer.net/2016/sync-algorithm.html. I used this concept on a totally different probject and utility: https://github.com/Jwink3101/notefile/blob/master/macOS_sync/macOStag_sync.py

I hope this helps!
